### ISSUE TITLE
Problem with _pages/schemas.md http://devicetree.org/schemas/interrupt-controller/arm,gic.yaml#

### ISSUE THREAD

**Issue by chankim** [devicetree-org/devicetree-website#106]
Please enter some details about the bug/issue so we can promptly resolve it. 
URL:  https://www.devicetree.org/schema/

when I try to open http://devicetree.org/schemas/interrupt-controller/arm,gic.yaml# it says there no such file.

**Comment by kylekirkby** [comment]
Hi @chankim,

As stated on the page (https://www.devicetree.org/schema/):

```
These are not the schemas you are looking for.

The schema URLs are just unique identifiers which is json-schema convention. The DT schemas exist within the dt-schema project and projects using dt-schema (e.g. Linux kernel). For dt-schema, the schema files are installed with the python module.
```
https://github.com/devicetree-org/dt-schema/blob/main/schemas/interrupt-controller.yaml
