### ISSUE TITLE
Confusing information about the v1.0 specification

### ISSUE THREAD

**Issue by 5frank** [devicetree-org/devicetree-website#13]
According to devicetree.org/faq/ and devicetree.org/specifications/ there is a v1.0 specification planned to be released in "aug. 2016", available at either devicetree.org or github.com/devicetree-org. However, there seems to be no pdf download, release tag or branch that is marked v1.0. I do not know if the this release is cancelled, delayed, same as  master branch, or if the project has moved.  Could someone please update the information on devicetree.org accordingly?

**Comment by kvekaria** [comment]
Yes good point!

It has been delayed. We are replanning and you are right we should be clear
about that on the website. I'll get that updated

Thanks
Kanta

**Comment by robherring** [comment]
@kvekaria, This page still needs fixing: https://www.devicetree.org/specifications/

**Comment by kvekaria** [comment]
Thanks for the nudge. Pull request created
