### ISSUE TITLE
Automatically generate release information from GitHub

### ISSUE THREAD

**Issue by glikely** [devicetree-org/devicetree-website#24]
Information about releases, pre-releases and release candidates is currently manually put into the website, but it should be possible to autogenerate that information from the devicetree-specification project releases page. Can this website be configured to automatically stay up to date with releases on GitHub?

**Comment by kylekirkby** [comment]
Hi Grant,

Which page on the DeviceTree.org site do you want to add this info? What information do you want exactly and is it [this](https://github.com/devicetree-org/devicetree-specification/releases) page you are looking to grab info about releases, pre-releases and release candidates from?

**Comment by kvekaria** [comment]
Hi Kyle
Thank you for updating the Homepage to display the latest release

Please also have this page pull directly from GitHub
https://www.devicetree.org/specifications/

Thanks
Kanta

**Comment by kylekirkby** [comment]
Hi Kanta,
I have PR open here for this issue - https://github.com/devicetree-org/devicetree-website/pull/29


Thanks,
Kyle

**Comment by kylekirkby** [comment]
I've updated the PR so that /specifications/ also grabs the required data from the DeviceTree Releases on GitHub via the GitHub API.

**Comment by kvekaria** [comment]
Thank you!
