### ISSUE TITLE
Redirect from /blog/ to non-existing /news/ is invalid

### ISSUE THREAD

**Issue by morancj** [devicetree-org/devicetree-website#82]
PR #81 , PR #62

**Comment by morancj** [comment]
Maybe you meant to link to [_pages/latest/](https://github.com/devicetree-org/devicetree-website/tree/develop/_pages/latest), given that page states `Find all DeviceTree related news and blogs here.`

**Comment by kylekirkby** [comment]
> Maybe you meant to link to [_pages/latest/](https://github.com/devicetree-org/devicetree-website/tree/develop/_pages/latest), given that page states `Find all DeviceTree related news and blogs here.`

https://github.com/devicetree-org/devicetree-website/pull/84

**Comment by morancj** [comment]
#83 #84 Apparently so
