### ISSUE TITLE
FAQ links to old repo

### ISSUE THREAD

**Issue by danrue** [devicetree-org/devicetree-website#92]
I don't know why, but at https://www.devicetree.org/faq/, "Devicetree Specification release repository" links to https://github.com/devicetree-org/devicetree-specification-released, which redirects to https://github.com/glikely/devicetree-specification-released, which was last updated 4 years ago.

**Comment by robherring** [comment]
That should link to https://github.com/devicetree-org/devicetree-specification/releases

We used to have a release repo until we started using GH releases.
