### ISSUE TITLE
Problem with _pages/latest.md

### ISSUE THREAD

**Issue by rihoward** [devicetree-org/devicetree-website#99]
URL:  https://www.devicetree.org/latest/
There are broken links on the page.

**Comment by pcolmer** [comment]
@kylekirkby 

```
/latest/index.html:
   https://www.linaro.org/blog/devicetree-specification-0.2-released/ [404]
   https://www.linaro.org/blog/bof-device-tree-secure-firmware-bud17-313/ [404]
   https://www.linaro.org/blog/introducing-devicetree-org/ [404]
```
Were these blogs part of the recent purge?

**Comment by kylekirkby** [comment]
@pcolmer Indeed.

**Comment by rihoward** [comment]
The link on that page  "Devicetree Specification v0.2 Released" still points to a bad endpoint --> https://www.linaro.org/blog/devicetree-specification-0_2-released/

**Comment by pcolmer** [comment]
Apologies, @rihoward. This has now been corrected. Thank you for bringing this to our attention.
